version: '3.7'
services:
  mysqlDB:
    image: mysql:8.0.11
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: jcquevedo84
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test_db
    ports:
      - 3306:3306
    volumes:
      - ./database/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./database/create.sql:/docker-entrypoint-initdb.d/create.sql
      - ./database/tables.sql:/docker-entrypoint-initdb.d/tables.sql
      - ./database/setup_data.sql:/docker-entrypoint-initdb.d/setup_data.sql
      - ./database/test_data.sql:/docker-entrypoint-initdb.d/test_data.sql
      - ./database/data:/var/lib/mysql
networks:
  default:
    name: mysql-db